language: nodejs

node_js: 10

install:
- npm install --global grunt-cli
- npm install

script:
- grunt

after_success:
- grunt trigger

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
