language: nodejs

node_js:
- 6

install:
- npm install --global ied
- ied install

script:
- grunt

after_success:
- sh trigger.sh

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
