name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 15
    uses: actions/setup-node@v1
    with:
     node-version: 15
  - run: npm install
  - run: grunt
 trigger:
  needs: lint
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 15
    uses: actions/setup-node@v1
    with:
     node-version: 15
  - run: npm install
  - run: grunt trigger
    env:
     TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
